// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/duelist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DuelistService_CreateCowboy_FullMethodName = "/duelist.DuelistService/CreateCowboy"
	DuelistService_GetCowboy_FullMethodName    = "/duelist.DuelistService/GetCowboy"
)

// DuelistServiceClient is the client API for DuelistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DuelistServiceClient interface {
	// สร้าง Cowboy ใหม่
	CreateCowboy(ctx context.Context, in *CreateCowboyRequest, opts ...grpc.CallOption) (*CowboyResponse, error)
	// ดึงข้อมูล Cowboy ตาม ID
	GetCowboy(ctx context.Context, in *GetCowboyRequest, opts ...grpc.CallOption) (*CowboyResponse, error)
}

type duelistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDuelistServiceClient(cc grpc.ClientConnInterface) DuelistServiceClient {
	return &duelistServiceClient{cc}
}

func (c *duelistServiceClient) CreateCowboy(ctx context.Context, in *CreateCowboyRequest, opts ...grpc.CallOption) (*CowboyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CowboyResponse)
	err := c.cc.Invoke(ctx, DuelistService_CreateCowboy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duelistServiceClient) GetCowboy(ctx context.Context, in *GetCowboyRequest, opts ...grpc.CallOption) (*CowboyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CowboyResponse)
	err := c.cc.Invoke(ctx, DuelistService_GetCowboy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DuelistServiceServer is the server API for DuelistService service.
// All implementations must embed UnimplementedDuelistServiceServer
// for forward compatibility.
type DuelistServiceServer interface {
	// สร้าง Cowboy ใหม่
	CreateCowboy(context.Context, *CreateCowboyRequest) (*CowboyResponse, error)
	// ดึงข้อมูล Cowboy ตาม ID
	GetCowboy(context.Context, *GetCowboyRequest) (*CowboyResponse, error)
	mustEmbedUnimplementedDuelistServiceServer()
}

// UnimplementedDuelistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDuelistServiceServer struct{}

func (UnimplementedDuelistServiceServer) CreateCowboy(context.Context, *CreateCowboyRequest) (*CowboyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCowboy not implemented")
}
func (UnimplementedDuelistServiceServer) GetCowboy(context.Context, *GetCowboyRequest) (*CowboyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCowboy not implemented")
}
func (UnimplementedDuelistServiceServer) mustEmbedUnimplementedDuelistServiceServer() {}
func (UnimplementedDuelistServiceServer) testEmbeddedByValue()                        {}

// UnsafeDuelistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DuelistServiceServer will
// result in compilation errors.
type UnsafeDuelistServiceServer interface {
	mustEmbedUnimplementedDuelistServiceServer()
}

func RegisterDuelistServiceServer(s grpc.ServiceRegistrar, srv DuelistServiceServer) {
	// If the following call panics, it indicates UnimplementedDuelistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DuelistService_ServiceDesc, srv)
}

func _DuelistService_CreateCowboy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCowboyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuelistServiceServer).CreateCowboy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuelistService_CreateCowboy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuelistServiceServer).CreateCowboy(ctx, req.(*CreateCowboyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuelistService_GetCowboy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCowboyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuelistServiceServer).GetCowboy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuelistService_GetCowboy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuelistServiceServer).GetCowboy(ctx, req.(*GetCowboyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DuelistService_ServiceDesc is the grpc.ServiceDesc for DuelistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DuelistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duelist.DuelistService",
	HandlerType: (*DuelistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCowboy",
			Handler:    _DuelistService_CreateCowboy_Handler,
		},
		{
			MethodName: "GetCowboy",
			Handler:    _DuelistService_GetCowboy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/duelist.proto",
}
