// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/duelist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CowboyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Health        int32                  `protobuf:"varint,3,opt,name=health,proto3" json:"health,omitempty"`
	Damage        int32                  `protobuf:"varint,4,opt,name=damage,proto3" json:"damage,omitempty"`
	Speed         int32                  `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,6,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CowboyResponse) Reset() {
	*x = CowboyResponse{}
	mi := &file_proto_duelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CowboyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CowboyResponse) ProtoMessage() {}

func (x *CowboyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_duelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CowboyResponse.ProtoReflect.Descriptor instead.
func (*CowboyResponse) Descriptor() ([]byte, []int) {
	return file_proto_duelist_proto_rawDescGZIP(), []int{0}
}

func (x *CowboyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CowboyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CowboyResponse) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *CowboyResponse) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CowboyResponse) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *CowboyResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type CreateCowboyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Health        int32                  `protobuf:"varint,3,opt,name=health,proto3" json:"health,omitempty"`
	Damage        int32                  `protobuf:"varint,4,opt,name=damage,proto3" json:"damage,omitempty"`
	Speed         int32                  `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,6,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCowboyRequest) Reset() {
	*x = CreateCowboyRequest{}
	mi := &file_proto_duelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCowboyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCowboyRequest) ProtoMessage() {}

func (x *CreateCowboyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_duelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCowboyRequest.ProtoReflect.Descriptor instead.
func (*CreateCowboyRequest) Descriptor() ([]byte, []int) {
	return file_proto_duelist_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCowboyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCowboyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCowboyRequest) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *CreateCowboyRequest) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CreateCowboyRequest) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *CreateCowboyRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type GetCowboyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCowboyRequest) Reset() {
	*x = GetCowboyRequest{}
	mi := &file_proto_duelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCowboyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCowboyRequest) ProtoMessage() {}

func (x *GetCowboyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_duelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCowboyRequest.ProtoReflect.Descriptor instead.
func (*GetCowboyRequest) Descriptor() ([]byte, []int) {
	return file_proto_duelist_proto_rawDescGZIP(), []int{2}
}

func (x *GetCowboyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_duelist_proto protoreflect.FileDescriptor

const file_proto_duelist_proto_rawDesc = "" +
	"\n" +
	"\x13proto/duelist.proto\x12\aduelist\"\x96\x01\n" +
	"\x0eCowboyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06health\x18\x03 \x01(\x05R\x06health\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x05R\x06damage\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x05R\x05speed\x12\x1a\n" +
	"\baccuracy\x18\x06 \x01(\x01R\baccuracy\"\x9b\x01\n" +
	"\x13CreateCowboyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06health\x18\x03 \x01(\x05R\x06health\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x05R\x06damage\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x05R\x05speed\x12\x1a\n" +
	"\baccuracy\x18\x06 \x01(\x01R\baccuracy\"\"\n" +
	"\x10GetCowboyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x98\x01\n" +
	"\x0eDuelistService\x12E\n" +
	"\fCreateCowboy\x12\x1c.duelist.CreateCowboyRequest\x1a\x17.duelist.CowboyResponse\x12?\n" +
	"\tGetCowboy\x12\x19.duelist.GetCowboyRequest\x1a\x17.duelist.CowboyResponseB,Z*github.com/yourusername/cowboy_arena/protob\x06proto3"

var (
	file_proto_duelist_proto_rawDescOnce sync.Once
	file_proto_duelist_proto_rawDescData []byte
)

func file_proto_duelist_proto_rawDescGZIP() []byte {
	file_proto_duelist_proto_rawDescOnce.Do(func() {
		file_proto_duelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_duelist_proto_rawDesc), len(file_proto_duelist_proto_rawDesc)))
	})
	return file_proto_duelist_proto_rawDescData
}

var file_proto_duelist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_duelist_proto_goTypes = []any{
	(*CowboyResponse)(nil),      // 0: duelist.CowboyResponse
	(*CreateCowboyRequest)(nil), // 1: duelist.CreateCowboyRequest
	(*GetCowboyRequest)(nil),    // 2: duelist.GetCowboyRequest
}
var file_proto_duelist_proto_depIdxs = []int32{
	1, // 0: duelist.DuelistService.CreateCowboy:input_type -> duelist.CreateCowboyRequest
	2, // 1: duelist.DuelistService.GetCowboy:input_type -> duelist.GetCowboyRequest
	0, // 2: duelist.DuelistService.CreateCowboy:output_type -> duelist.CowboyResponse
	0, // 3: duelist.DuelistService.GetCowboy:output_type -> duelist.CowboyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_duelist_proto_init() }
func file_proto_duelist_proto_init() {
	if File_proto_duelist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_duelist_proto_rawDesc), len(file_proto_duelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_duelist_proto_goTypes,
		DependencyIndexes: file_proto_duelist_proto_depIdxs,
		MessageInfos:      file_proto_duelist_proto_msgTypes,
	}.Build()
	File_proto_duelist_proto = out.File
	file_proto_duelist_proto_goTypes = nil
	file_proto_duelist_proto_depIdxs = nil
}
